### ISSUE TITLE
Suddenly started getting error when attempting `require('console-testing-library/pure')` 

### ISSUE THREAD

**Issue by robross0606** [kevin940726/console-testing-library#18]
I've suddenly started getting this error when doing:
```
const { createConsole, mockConsole } = require('console-testing-library/pure')
```
It only throws the error when attempting to run a single Jest test file:
```
internal/modules/cjs/loader.js:1080
      throw new ERR_REQUIRE_ESM(filename, parentPath, packageJsonPath);
      ^

Error [ERR_REQUIRE_ESM]: Must use import to load ES Module: C:\Code\ncp\study-design-service\node_modules\console-testing-library\dist\pure.js
require() of ES modules is not supported.
require() of C:\Code\ncp\study-design-service\node_modules\console-testing-library\dist\pure.js from C:\Code\ncp\study-design-service\src\__tests__\resolvers\study-event-resolvers.test.js is an ES module file as it is a .js file whose nearest parent package.json contains "type": "module" which defines all .js files in that package scope as ES modules.
Instead rename pure.js to end in .cjs, change the requiring code to use import(), or remove "type": "module" from C:\Code\ncp\study-design-service\node_modules\console-testing-library\package.json.

    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1080:13)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (C:\Code\ncp\study-design-service\src\__tests__\resolvers\study-event-resolvers.test.js:5:40)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14) {
  code: 'ERR_REQUIRE_ESM'
```

**Comment by kevin940726** [comment]
Which Node version are you using? Are you using babel to transpile your code in Jest? A minimal repro repo would be very helpful! :)

**Comment by robross0606** [comment]
node: 14.15.5
npm: 7.5.6

To my knowledge I'm not using babel to transpile in Jest.  Never have.  I have two branches of the same repo and only one is doing this.  I'd love to provide a minimal repro if I had the slightest idea what triggered it to start happening.

**Comment by robross0606** [comment]
This turns out to be related to `npm` v7 bugs.  The new version being made `latest` has caused all sorts of problems.  Many, many bugs.  I've returned to npm v6 and all is well.

**Comment by kevin940726** [comment]
Interesting, I've encountered some issues with npm 7 as well. Glad that there's a workaround for that, but let's keep this open until the issue has been resolved.
